#FROM nginx:stable-alpine
#COPY ./../../sima-develop/docker/nginx/* /etc/nginx/conf.d/
#COPY ./../../sima-develop /var/www/html
#RUN chown nginx:nginx /var/www/html -R
#RUN chmod 775 /var/www/html/public -R
#RUN chmod 775 /var/www/html/storage -R
#RUN chmod 775 /var/www/html/bootstrap/cache -R
        #    -   ./sima-develop:/var/www/html
#            -   ./sima-develop/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        #    -   ./sima-develop/docker/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
        #    -   ./sima-develop/docker/nginx/front.conf:/etc/nginx/conf.d/front.conf
        #    -   ./sima-develop/docker/nginx/wildcard_nlho_ir.crt:/etc/nginx/conf.d/wildcard_nlho_ir.crt
        #    -   ./sima-develop/docker/nginx/wildcard_nlho_ir.key:/etc/nginx/conf.d/wildcard_nlho_ir.key

